cargo-features = ["edition"]

[package]
name = "arangors"
version = "0.1.0"
edition = '2018'
authors = ["Guoli Lyu <guoli-lv@hotmail.com>"]
readme = "README.md"
license = "MIT"
description = "Rust driver for ArangoDB"
repository = "https://github.com/Guoli-Lyu/arangors"
documentation = "https://docs.rs/arangors"
keywords = ["nosql", "database", "client", "driver", "arangoDB"]

[badges]
travis-ci = { repository = "Guoli-Lyu/arangors", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = ["rocksdb"]
cluster = []
enterprise = []
mmfiles = []
rocksdb = []

[dependencies]
failure = "0.1.2"
regex = "1.0.4"
reqwest = "0.8.8"
serde = "1.0.76"
serde_json = "1.0.26"
serde_derive = "1.0.76"
log = "0.4.5"
url = "1.7.1"

[dev-dependencies]
pretty_env_logger = "0.2.4"
pretty_assertions = "0.5.1"
dotenv = "0.13.0"

[package.metadata.docs.rs]
all-features = true
features = [
    "cluster",
    "enterprise",
    "mmfiles",
    "rocksdb",
]