cargo-features = ["edition"]

[package]
name = "arango_rs"
version = "0.1.0"
authors = ["Guoli Lyu <guoli-lv@hotmail.com>"]
readme = "README.md"
keywords = ["nosql", "database", "client", "driver", "arangoDB","graph databse"]
license = "MIT"
edition = '2018'

[dependencies]
failure = "0.1.2"
futures = "0.1.23"
hyper = "0.12.9"
regex = "1.0.4"
reqwest = "0.8.8"
serde = "1.0.76"
serde_json = "1.0.26"
serde_derive = "1.0.76"

[dev-dependencies]
pretty_env_logger = "0.2.4"
pretty_assertions = "0.5.1"
log = "0.4.5"
tokio = "0.1.8"