cargo-features = ["edition"]

[package]
name = "arangors"
version = "0.1.0"
authors = ["Guoli Lyu <guoli-lv@hotmail.com>"]
readme = "README.md"
keywords = ["nosql", "database", "client", "driver", "arangoDB","graph databse"]
license = "MIT"
edition = '2018'

[badges]
travis-ci = { repository = "Guoli-Lyu/arangors", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = ["rocksdb"]
cluster = []
enterprise = []
mmfiles = []
rocksdb = []

[dependencies]
failure = "0.1.2"
futures = "0.1.24"
hyper = "0.12.9"
regex = "1.0.4"
reqwest = "0.8.8"
serde = "1.0.76"
serde_json = "1.0.26"
serde_derive = "1.0.76"
log = "0.4.5"

[dev-dependencies]
pretty_env_logger = "0.2.4"
pretty_assertions = "0.5.1"
dotenv = "0.13.0"

[package.metadata.docs.rs]
all-features = true
features = [
    "cluster",
    "enterprise",
    "mmfiles",
    "rocksdb",
]